name: Fetch Ocicat Holders

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run JavaScript fetch script
        run: node scripts/fetchOcicatHolders.js

      - name: Commit updated holders.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add public/holders.json
          git commit -m "Update holders.json [auto]" || echo "No changes to commit"
          git push
